/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author ale_9
 */
public class Parametros extends javax.swing.JFrame {

    Sensores Oper = new Sensores();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtValorActual = new javax.swing.JLabel();
        spMin = new javax.swing.JSpinner();
        spMax = new javax.swing.JSpinner();
        txtUnidad1 = new javax.swing.JLabel();
        txtUnidad2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtUnidad3 = new javax.swing.JLabel();
        cbSensor = new javax.swing.JComboBox<>();
        txtSensor = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        JMAjustes = new javax.swing.JMenu();
        JMParametros = new javax.swing.JMenuItem();
        JMIntervalos = new javax.swing.JMenuItem();
        JMPotenciaBombas = new javax.swing.JMenuItem();
        JMDispositivos = new javax.swing.JMenu();
        JMAgregar = new javax.swing.JMenuItem();
        JMEliminar = new javax.swing.JMenuItem();
        JMOnOff = new javax.swing.JMenu();
        JMReportes = new javax.swing.JMenu();
        JMSalir = new javax.swing.JMenu();
        JMCerrarSesion = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        JMSalirTodo = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Parámetros");
        setBounds(new java.awt.Rectangle(450, 50, 500, 600));
        setMinimumSize(new java.awt.Dimension(293, 23));
        setPreferredSize(new java.awt.Dimension(500, 500));
        addWindowStateListener(new java.awt.event.WindowStateListener() {
            public void windowStateChanged(java.awt.event.WindowEvent evt) {
                formWindowStateChanged(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel3.setText("Valor actual");

        jLabel4.setText("Valores mínimos");

        jLabel5.setText("Valores máximos");

        txtValorActual.setText("---");

        jLabel1.setText("Seleciona sensor:");

        cbSensor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "(Seleccionar sensor)", "Sens. Humedad 1", "Sens. Temperatura 1", "Sens. Humedad 2", "Sens. Temperatura 2" }));
        cbSensor.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbSensorItemStateChanged(evt);
            }
        });

        txtSensor.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        btnRegistrar.setText("Registrar");
        btnRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegistrarMouseClicked(evt);
            }
        });
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        JMAjustes.setText("Ajustes");

        JMParametros.setText("Parámetros");
        JMParametros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JMParametrosMouseClicked(evt);
            }
        });
        JMAjustes.add(JMParametros);

        JMIntervalos.setText("Intervalos");
        JMAjustes.add(JMIntervalos);

        JMPotenciaBombas.setText("Potencia de bombas");
        JMAjustes.add(JMPotenciaBombas);

        jMenuBar1.add(JMAjustes);

        JMDispositivos.setText("Dispositivos");

        JMAgregar.setText("Agregar");
        JMDispositivos.add(JMAgregar);

        JMEliminar.setText("Eliminar");
        JMDispositivos.add(JMEliminar);

        jMenuBar1.add(JMDispositivos);

        JMOnOff.setText("ON/OFF");
        jMenuBar1.add(JMOnOff);

        JMReportes.setText("Reportes");
        jMenuBar1.add(JMReportes);

        JMSalir.setText("Salir");

        JMCerrarSesion.setText("Cerrar sesión");
        JMSalir.add(JMCerrarSesion);
        JMSalir.add(jSeparator1);

        JMSalirTodo.setText("Salir");
        JMSalirTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMSalirTodoActionPerformed(evt);
            }
        });
        JMSalir.add(JMSalirTodo);

        jMenuBar1.add(JMSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                        .addComponent(cbSensor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(spMax, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(spMin, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtValorActual)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtUnidad1)
                            .addComponent(txtUnidad2)
                            .addComponent(txtUnidad3))))
                .addGap(43, 43, 43))
            .addGroup(layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnRegistrar)
                    .addComponent(txtSensor))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbSensor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(txtSensor)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtValorActual)
                    .addComponent(txtUnidad1))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(spMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUnidad2))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(spMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUnidad3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(btnRegistrar)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JMParametrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JMParametrosMouseClicked
        Parametros P1 = new Parametros();
        P1.setVisible(true);
    }//GEN-LAST:event_JMParametrosMouseClicked

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void formWindowStateChanged(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowStateChanged
        
    }//GEN-LAST:event_formWindowStateChanged

    private void cbSensorItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbSensorItemStateChanged
        // TODO add your handling code here:
        String sensor= (String) cbSensor.getSelectedItem();
        Oper.SelecionarSensor(sensor);
        txtSensor.setText(Oper.Nombre);
        txtUnidad1.setText(Oper.U1);
        txtUnidad2.setText(Oper.U2);
        txtUnidad3.setText(Oper.U3);
        txtValorActual.setText(String.valueOf(Oper.ValorActual));
        spMin.setValue(Oper.min);
        spMax.setValue(Oper.max);
    }//GEN-LAST:event_cbSensorItemStateChanged

    private void btnRegistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarMouseClicked
        // TODO add your handling code here:
        String sensor= (String) cbSensor.getSelectedItem();
        int ValorMax = (int) spMax.getValue();
        int ValorMin = (int) spMin.getValue();
        Oper.RegistrarParametros(sensor, ValorMax, ValorMin);
        Oper.SelecionarSensor(sensor);
        spMin.setValue(Oper.min);
        spMax.setValue(Oper.max);
    }//GEN-LAST:event_btnRegistrarMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
      
    }//GEN-LAST:event_formWindowOpened

    private void JMSalirTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMSalirTodoActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_JMSalirTodoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Parametros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Parametros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Parametros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Parametros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Parametros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem JMAgregar;
    private javax.swing.JMenu JMAjustes;
    private javax.swing.JMenuItem JMCerrarSesion;
    private javax.swing.JMenu JMDispositivos;
    private javax.swing.JMenuItem JMEliminar;
    private javax.swing.JMenuItem JMIntervalos;
    private javax.swing.JMenu JMOnOff;
    private javax.swing.JMenuItem JMParametros;
    private javax.swing.JMenuItem JMPotenciaBombas;
    private javax.swing.JMenu JMReportes;
    private javax.swing.JMenu JMSalir;
    private javax.swing.JMenuItem JMSalirTodo;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<String> cbSensor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JSpinner spMax;
    private javax.swing.JSpinner spMin;
    private javax.swing.JLabel txtSensor;
    private javax.swing.JLabel txtUnidad1;
    private javax.swing.JLabel txtUnidad2;
    private javax.swing.JLabel txtUnidad3;
    private javax.swing.JLabel txtValorActual;
    // End of variables declaration//GEN-END:variables

    public Parametros() {
        initComponents();
    }

}
